pool:
  vmImage: 'ubuntu-16.04'

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - docs
      - version.properties
steps:
  - script: |
      curl --location https://github.com/ethankhall/inc/releases/download/v0.1.6/inc-linux-0.1.6 -o ~/inc
      curl --location https://github.com/ethankhall/crom/releases/download/v0.1.5/crom-linux -o ~/crom
      chmod +x ~/inc ~/crom
    displayName: 'Prepare the machine'

  - script: |
      ~/crom update-version --pre-release release
      ~/inc exec build
      ~/inc exec package

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'

  - task: CopyFiles@2
    inputs:
      sourceFolder: build/release-dir
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: artifacts

  - script: |
      ~/crom tag-version --source local,github --ignore-changes
      ~/crom upload-artifacts gadget.zip=build/webapp/gadget-release/gadget.zip
      export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
      echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      sudo apt-get update && sudo apt-get install google-cloud-sdk

      echo $GCP_SERVICE_TOKEN | base64 -d  > ${HOME}/gcloud-service-key.json
      gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      gcloud --quiet config set project ${GCP_PROJECT_ID}

      ./gradlew jib -Djib.to.auth.username="oauth2accesstoken" -Djib.to.auth.password="$(gcloud auth print-access-token)"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

